# -*- coding: utf-8 -*-
"""list-comprehension

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ZEnWfhb6UjK0SywLCq8uBK7Awio44bOe

# リスト内包表記を学ぼう

## Summary
今回の課題の目標は、リスト内包表記を使いこなそう！です。
pythonでは新しいリストを作成する際に、かなりシンプルに書くことができる構文があります。それを用いることで、例えばリファクタリングの一環としてコードの可読性を上手にあげていくことができるかと思います。
ただ、注意しなければいけない点もあり、例えば、たくさんの処理を1行になどすると逆に読みにくくなることも多いですその点は意識しながら利用していきましょう。
リスト内包表記については[こちらの記事](https://datawokagaku.com/python_grammar1/)を参考にしてください．



## 課題概要
2つの課題をpythonで実現してください！ファイル名は`list_comprehension.py`としてください。

1つ目の課題は、温度の単位変換です。温度にはいくつかの単位がありますが、今回はCelsius温度とFahrenheit温度の変換をやってみましょう！（摂氏と華氏のこと）

2つ目の課題は、`integer`の100以下の自然数を入力すると、その値の100以下の倍数がすべて含まれるリストが生成されるようコードを書いてください。例えば、`30`をインプットすると、`[30, 60, 90]`が返ってくるように、です。




### 課題 ①：温度単位変更でリスト内包表記を学ぼう
Celsius温度のリストをリスト内包表記を用いて、Fahrenheit温度のリストに変換して出力してください。変換の計算式は、`1.8*Celsius温度 + 32`です。
例えば、celsius = [10, 35, 21, 43]であれば、fahrenheit = [50.0, 95.0, 69.8, 109.4]となるはずです。(小数点の制御にも注意！)



### 課題 ②：指定自然数の100以下の倍数一覧生成でリスト内包表記を学ぼう

100以下の自然数を入力すると、その値の100以下の倍数がすべて含まれるリストが生成されるコードを書いてみましょう！
ノーヒントです！
"""

#課題1
celsius_list = [10, 35, 21, 43]
fahrenheit_list = [round(1.8*celsius + 32, 1) for celsius in celsius_list]
fahrenheit_list

#課題2
n = int(input("100以下の自然数を入力してください。"))
[i for i in range(1,n+1) if  n % i == 0 and 1 <= n <= 100]

